name = "jinbean-admin"
main = "./.vercel/output/static/_worker.js"
compatibility_date = "2024-07-04"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./.vercel/output/static"

[env.production]
name = "jinbean-admin"

[env.staging]
name = "jinbean-admin-staging"

# 环境变量配置
[vars]
NODE_ENV = "production"

# 绑定配置（如果需要数据库等）
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxx"
# preview_id = "xxx" 